### ISSUE TITLE
Restart echobot automatically on failure

### ISSUE THREAD

**Issue by link2xt** [deltachat/chatmail#141]
Right after new server setup echobot did not work for me because it already crashed due to missing DNS:
```
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for mail.c20.testrun.org:465 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for mail.c20.testrun.org:587 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:186: Failed to connect to 95.216.165.93:465: connection failure: Connection refused (os error 111).
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:186: Failed to connect to 95.216.165.93:587: connection failure: Connection refused (os error 111).
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for imap.c20.testrun.org:993 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for imap.c20.testrun.org:143 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for mail.c20.testrun.org:993 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for mail.c20.testrun.org:143 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for imap.c20.testrun.org:993 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for imap.c20.testrun.org:143 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for mail.c20.testrun.org:993 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:38 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for mail.c20.testrun.org:143 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:43 c20 echobot[7192]: WARNING:root:src/imap.rs:400: Cannot login as "echo@c20.testrun.org". Please check if the email address and the password are correct. (no response: code: None, info: Some("[A>
Dec 19 18:05:50 c20 echobot[7192]: WARNING:root:src/imap.rs:400: Cannot login as "echo@c20.testrun.org". Please check if the email address and the password are correct. (no response: code: None, info: Some("[A>
Dec 19 18:05:50 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for imap.c20.testrun.org:993 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:50 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for imap.c20.testrun.org:143 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:50 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for mail.c20.testrun.org:993 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:50 c20 echobot[7192]: WARNING:root:src/net.rs:56: DNS resolution for mail.c20.testrun.org:143 failed: DNS lookup failure: failed to lookup address information: Name does not resolve.
Dec 19 18:05:58 c20 echobot[7192]: WARNING:root:src/imap.rs:400: Cannot login as "echo". Please check if the email address and the password are correct. (no response: code: None, info: Some("[AUTHENTICATIONFAI>
Dec 19 18:06:03 c20 echobot[7192]: WARNING:root:src/imap.rs:400: Cannot login as "echo". Please check if the email address and the password are correct. (connection lost)
Dec 19 18:06:03 c20 echobot[7192]: Exception in thread Thread-4 (configure):
Dec 19 18:06:03 c20 echobot[7192]: Traceback (most recent call last):
Dec 19 18:06:03 c20 echobot[7192]:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Dec 19 18:06:03 c20 echobot[7192]:     self.run()
Dec 19 18:06:03 c20 echobot[7192]:   File "/usr/lib/python3.11/threading.py", line 975, in run
Dec 19 18:06:03 c20 echobot[7192]:     self._target(*self._args, **self._kwargs)
Dec 19 18:06:03 c20 echobot[7192]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/deltachat_rpc_client/client.py", line 202, in configure
Dec 19 18:06:03 c20 echobot[7192]:     super().configure(email, password, **kwargs)
Dec 19 18:06:03 c20 echobot[7192]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/deltachat_rpc_client/client.py", line 87, in configure
Dec 19 18:06:03 c20 echobot[7192]:     self.account.configure()
Dec 19 18:06:03 c20 echobot[7192]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/deltachat_rpc_client/account.py", line 81, in configure
Dec 19 18:06:03 c20 echobot[7192]:     self._rpc.configure(self.id)
Dec 19 18:06:03 c20 echobot[7192]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/deltachat_rpc_client/rpc.py", line 162, in method
Dec 19 18:06:03 c20 echobot[7192]:     raise JsonRpcError(response["error"])
Dec 19 18:06:03 c20 echobot[7192]: deltachat_rpc_client.rpc.JsonRpcError: {'code': -1, 'message': 'Trying imap: echo@c20.testrun.org@imap.c20.testrun.org:993 security=Ssl certificate_checks=strict oauth2=false>
```

I have set up DNS, but the bot did not recover, I had to restart it.

Bot should crash and systemd should retry starting it after each crash until it works.

**Comment by missytake** [comment]
Hm, that's not easy with the RPC bindings. Basically, `run_forever()` doesn't give you anything useful you could crash on. `run_until(get_disconnected)` might be a way.

**Comment by missytake** [comment]
Ah, or `run_until(maybe_network, False)` might work? I'll look up the return values of maybe_network.

**Comment by missytake** [comment]
Hm, I suspect that simply checking `maybe_network() == False` would lead to restarts every time the network has *not* changed.

it seems we actually need this function: https://github.com/deltachat/deltachat-core-rust/blob/main/src/scheduler.rs#L222
But it isn't available from the RPC client.
