### ISSUE TITLE
Creating echo@staging.testrun.org doesn't work: Authentication Failed.

### ISSUE THREAD

**Issue by missytake** [deltachat/chatmail#277]
- Operating System (Linux/Mac/Windows/iOS/Android): Debian 12
- Delta Chat Version: Core v1.137.4
- Expected behavior: If you write to echo@staging.testrun.org, you get your message back as a reply.
- Actual behavior: echo@staging.testrun.org doesn't reply, because the account fails to get created.
- Steps to reproduce the problem:
  - deploy staging.testrun.org
  - send a message to echo@staging.testrun.org
  - see in the logs that the echobot service failed: `journalctl -u echobot.service`
- Logs:

```
Mai 02 11:19:14 staging echobot[13517]: [2024-05-02T11:19:14Z INFO  deltachat_rpc_server] Starting with accounts directory `accounts`.
Mai 02 11:19:14 staging echobot[13517]: [2024-05-02T11:19:14Z INFO  deltachat_rpc_server] Creating JSON-RPC API.
Mai 02 11:19:14 staging echobot[13515]: INFO:root:Running deltachat core v1.137.4
Mai 02 11:19:23 staging echobot[13517]: [2024-05-02T11:19:23Z INFO  deltachat_rpc_server] EOF reached on stdin
Mai 02 11:19:23 staging echobot[13515]: Traceback (most recent call last):
Mai 02 11:19:23 staging echobot[13515]:   File "/usr/local/lib/chatmaild/venv/bin/echobot", line 8, in <module>
Mai 02 11:19:23 staging echobot[13515]:     sys.exit(main())
Mai 02 11:19:23 staging echobot[13515]:              ^^^^^^
Mai 02 11:19:23 staging echobot[13515]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/chatmaild/echo.py", line 82, in main
Mai 02 11:19:23 staging echobot[13515]:     bot.configure(email, password)
Mai 02 11:19:23 staging echobot[13515]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/deltachat_rpc_client/client.py", line 202, in configure
Mai 02 11:19:23 staging echobot[13515]:     super().configure(email, password, **kwargs)
Mai 02 11:19:23 staging echobot[13515]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/deltachat_rpc_client/client.py", line 87, in configure
Mai 02 11:19:23 staging echobot[13515]:     self.account.configure()
Mai 02 11:19:23 staging echobot[13515]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/deltachat_rpc_client/_utils.py", line 201, in wrapper
Mai 02 11:19:23 staging echobot[13515]:     return f()
Mai 02 11:19:23 staging echobot[13515]:            ^^^
Mai 02 11:19:23 staging echobot[13515]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/deltachat_rpc_client/_utils.py", line 193, in f
Mai 02 11:19:23 staging echobot[13515]:     generator.send(res())
Mai 02 11:19:23 staging echobot[13515]:                    ^^^^^
Mai 02 11:19:23 staging echobot[13515]:   File "/usr/local/lib/chatmaild/venv/lib/python3.11/site-packages/deltachat_rpc_client/rpc.py", line 28, in __call__
Mai 02 11:19:23 staging echobot[13515]:     raise JsonRpcError(response["error"])
Mai 02 11:19:23 staging echobot[13515]: deltachat_rpc_client.rpc.JsonRpcError: {'code': -1, 'message': 'Cannot login as "echo@staging.testrun.org". Please check if the email address and the password are correct.\n\nno response: code: None, info: Some("[AUTHENTICATIONFAILED] Authentication failed.")'}
Mai 02 11:19:23 staging systemd[1]: echobot.service: Main process exited, code=exited, status=1/FAILURE
Mai 02 11:19:23 staging systemd[1]: echobot.service: Failed with result 'exit-code'.
```

**Comment by missytake** [comment]
> Maybe `VRFY` test creates `echo@staging.testrun.org`, but then I don't know where the password comes from.
> 
> Or: someone is running Delta Chat with echobot configured during debugging and now logs in faster than CI every time.

I freshly deployed chatmail on c3, and echobot service works. I didn't run the VRFY test yet though. I'll try to delay the VRFY test by a minute and see whether it works on staging as well then (unlikely, but let's see).

**Comment by missytake** [comment]
Wow. Seems it's indeed the VRFY test.
