### ISSUE TITLE
iroh isn't installed by cmdeploy

### ISSUE THREAD

**Issue by jagtalon** [deltachat/chatmail#449]
On Debian 12 amd64,  I got a message that iroh-relay binary is missing when running `cmdeploy run`:

```
--> Starting operation: Download iroh-relay 
    [chika.aangat.lahat.computer] /usr/local/bin/iroh-relay: FAILED
    [chika.aangat.lahat.computer] sha256sum: WARNING: 1 computed checksum did NOT match
    [chika.aangat.lahat.computer] sh: 1: curl: not found
    [chika.aangat.lahat.computer] 
    [chika.aangat.lahat.computer] gzip: stdin: unexpected end of file
    [chika.aangat.lahat.computer] tar: This does not look like a tar archive
    [chika.aangat.lahat.computer] tar: ./iroh-relay: Not found in archive
    [chika.aangat.lahat.computer] tar: Exiting with failure status due to previous errors
    [chika.aangat.lahat.computer] Error: executed 0 commands

--> Disconnecting from hosts...
--> pyinfra error: No hosts remaining!
Traceback (most recent call last):
  File "/home/jag/chatmail/venv/bin/cmdeploy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jag/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 349, in main
    res = args.func(args, out, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jag/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 89, in run_cmd
    retcode = out.check_call(cmd, env=env)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jag/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 258, in check_call
    return subprocess.check_call(arg, shell=True, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pyinfra --ssh-user root chika.aangat.lahat.computer /home/jag/chatmail/cmdeploy/src/cmdeploy/deploy.py -y' returned non-zero exit status 1.
```

**Comment by missytake** [comment]
Does running `apt install curl` on the server, and rerunning `cmdeploy run`, fix it? Maybe we forgot to install it as a dependency.

**Comment by jagtalon** [comment]
Ah yes the issue is that I'm missing curl! Ty @missytake !

**Comment by missytake** [comment]
Then we need to add curl ;) then we can close the issue :)
