### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by dillfrescott** [deltachat/chatmail#458]
```
--> Starting operation: Install Dovecot 
    [chat.dill.moe] Reading package lists...
    [chat.dill.moe] Building dependency tree...
    [chat.dill.moe] Reading state information...
    [chat.dill.moe] Some packages could not be installed. This may mean that you have
    [chat.dill.moe] requested an impossible situation or if you are using the unstable
    [chat.dill.moe] distribution that some required packages have not yet been created
    [chat.dill.moe] or been moved out of Incoming.
    [chat.dill.moe] The following information may help to resolve the situation:
    [chat.dill.moe] 
    [chat.dill.moe] The following packages have unmet dependencies:
    [chat.dill.moe]  dovecot-core : Depends: libc6 (>= 2.36) but 2.35-0ubuntu3.8 is to be installed
    [chat.dill.moe]                 Depends: libicu72 (>= 72.1~rc-1~) but it is not installable
    [chat.dill.moe]                 Depends: libzstd1 (>= 1.5.2) but 1.4.8+dfsg-3build1 is to be installed
    [chat.dill.moe]  dovecot-imapd : Depends: libzstd1 (>= 1.5.2) but 1.4.8+dfsg-3build1 is to be installed
    [chat.dill.moe] E: Unable to correct problems, you have held broken packages.
    [chat.dill.moe] Error: executed 0 commands

--> Disconnecting from hosts...
--> pyinfra error: No hosts remaining!
Traceback (most recent call last):
  File "/home/cross/Downloads/chatmail/venv/bin/cmdeploy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cross/Downloads/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 348, in main
    res = args.func(args, out, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cross/Downloads/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 89, in run_cmd
    retcode = out.check_call(cmd, env=env)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cross/Downloads/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 257, in check_call
    return subprocess.check_call(arg, shell=True, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pyinfra --ssh-user root chat.dill.moe /home/cross/Downloads/chatmail/cmdeploy/src/cmdeploy/deploy.py -y' returned non-zero exit status 1.
```

On ubuntu 22.04

**Comment by dillfrescott** [comment]
Nevermind wrong ubuntu version you need to use 20.04 apparently

**Comment by missytake** [comment]
Hm, we actually recommend Debian 12 instead of Ubuntu... Isn't 20.04 EOL already? Not sure if using 20.04 is viable.

**Comment by missytake** [comment]
Please re-open if it doesn't work with Debian 12 :)

**Comment by AspireSus** [comment]
Got the same error as dillfrescott and I downgrade  

libc6: Installed: 2.35-0ubuntu3.9, [installed]
libzstd1: Installed: 1.4.8+dfsg-3build1, [installed]
libicu72: Installed: 72.1-3, [installed,local]

After this the "Starting operation: Install Dovecot" got: 

dovecot-core : 
Depends: libc6 (>= 2.36) but 2.35-0ubuntu3.9 is to be installed
Depends: libzstd1 (>= 1.5.2) but 1.4.8+dfsg-3build1 is to be installed
dovecot-imapd : 
Depends: libzstd1 (>= 1.5.2) but 1.4.8+dfsg-3build1 is to be

"scripts/cmdeploy" on with Debian12 got the same error described by dillfrescott
"Nevermind wrong ubuntu version you need to use 20.04 apparently"

**Comment by missytake** [comment]
@AspireSus can you send me the error you get with Debian 12?
